# --------------------------------------
# Hexo Butterfly Theme Configuration
# If you have any questions, please refer to the documentation
# Chinese: https://butterfly.js.org/
# --------------------------------------

# --------------------------------------
# Navigation Settings
# --------------------------------------
nav:
  logo: /images/logo.webp

menu:
  首页: / || fa-solid fa-house
  归档: /archives/ || fa-solid fa-box-archive
  标签: /tags/ || fa-solid fa-tags
  分类: /categories/ || fa-solid fa-folder-tree
  关于: /about/ || fa-solid fa-user

# --------------------------------------
# Code Blocks Settings
# --------------------------------------
code_blocks:
  theme: false
  height_limit: 512
  fullpage: true

# Social media links
social:
  fa-solid fa-envelope: mailto:mtueih.org@outlook.com || Email || '#0078D4'

# --------------------------------------
# Image Settings
# --------------------------------------
favicon: /images/favicon.webp
avatar:
  img: /images/avatar.webp

default_top_img: /images/wallpaper-0-1.webp
index_img: /images/wallpaper-0.webp
archive_img:
tag_img:
tag_per_img:
category_img:
category_per_img:

footer_img: /images/wallpaper-0.webp

error_img:
  flink: /images/friend_404.gif
  post_page: /images/404.jpg

error_404:
  enable: true
  subtitle: 页面没有找到
  background: /images/error-page.png


post_meta:
  page:
    date_format: relative
    label: false
  post:
    position: center

# --------------------------------------
# Index page settings
# --------------------------------------
# The subtitle on homepage
subtitle:
  enable: true
  sub:
    - 且听且忘且随风，且行且看且从容。
    - 少年不识愁滋味，爱上层楼。爱上层楼，为赋新词强说愁。而今识尽愁滋味，欲说还休。欲说还休，却道“天凉好个秋”！

index_layout: 2

index_post_content:
  method: 2
  length: 256

# --------------------------------------
# Post Settings
# --------------------------------------
toc:
  number: false
  style_simple: true

post_copyright:
  decode: true
  author_href: https://github.com/mtueih/


# Related Articles
related_post:
  enable: true
  # Number of posts displayed
  limit: 8
  # Choose: created / updated
  date_type: created

# Choose: 1 / 2 / false
# 1: The 'next post' will link to old post
# 2: The 'next post' will link to new post
# false: disable pagination
post_pagination: 2

# Displays outdated notice for a post
noticeOutdate:
  enable: true
  # Style: simple / flat
  style: flat
  # When will it be shown
  limit_day: 1024
  # Position: top / bottom
  position: top
  message_prev: 距离上次更新已过去
  message_next: 天，文章内容可能已过时。

# --------------------------------------
# Footer Settings
# --------------------------------------
footer:
  nav:
  owner:
    enable: true
    since: 2026
  # Copyright of theme and framework
  copyright:
    enable: true
    version: true
  custom_text:

# --------------------------------------
# Aside Settings
# --------------------------------------

aside:
  enable: true
  hide: false
  # Show the button to hide the aside in bottom right button
  button: true
  mobile: true
  # Position: left / right
  position: right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description: 且听且忘且随风，且行且看且从容。
    button:
      enable: true
      icon: fab fa-github
      text: 我的 Github 主页
      link: https://github.com/mtueih
  card_announcement:
    enable: true
    content: 欢迎访问我的博客，获取更多技术干货和文章更新！
  card_recent_post:
    enable: true
    # If set 0 will show all
    limit: 8
    # Sort: date / updated
    sort: date
    sort_order:
  card_newest_comments:
    enable: true
    sort_order:
    limit: 8
    # Unit: mins, save data to localStorage
    storage: 1
    avatar: true
  card_categories:
    enable: true
    # If set 0 will show all
    limit: 8
    # Choose: none / true / false
    expand: true
    sort_order:
  card_tags:
    enable: true
    # If set 0 will show all
    limit: 32
    color: true
    # Order of tags, random/name/length
    orderby: random
    # Sort of order. 1, asc for ascending; -1, desc for descending
    order: 1
    sort_order:
  card_archives:
    enable: true
    # Type: monthly / yearly
    type: monthly
    # Eg: YYYY年MM月
    format: YYYY 年 M 月
    # Sort of order. 1, asc for ascending; -1, desc for descending
    order: -1
    # If set 0 will show all
    limit: 16
    sort_order:
  card_post_series:
    enable: true
    # The title shows the series name
    series_title: true
    # Order by title or date
    orderBy: 'date'
    # Sort of order. 1, asc for ascending; -1, desc for descending
    order: -1
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order:
    # Time difference between publish date and now
    # Formal: Month/Day/Year Time or Year/Month/Day Time
    # Leave it empty if you don't enable this feature
    runtime_date:

# --------------------------------------
# Bottom right button
# --------------------------------------

# Read Mode
readmode: true

# Dark Mode
darkmode:
  enable: true
  # Toggle Button to switch dark/light mode
  button: true
  # Switch dark/light mode automatically
  # autoChangeMode: 1  Following System Settings, if the system doesn't support dark mode, it will switch dark mode between 6 pm to 6 am
  # autoChangeMode: 2  Switch dark mode between 6 pm to 6 am
  # autoChangeMode: false
  autoChangeMode: 1
  # Set the light mode time. The value is between 0 and 24. If not set, the default value is 6 and 18
  start: 6
  end: 22

# Show scroll percent in scroll-to-top button
rightside_scroll_percent: true

# --------------------------------------
# Global Settings
# --------------------------------------

photofigcaption: true

copy:
  enable: true
  # Add the copyright information after copied content
  copyright:
    enable: true
    limit_count: 512

# Need to install the hexo-wordcount plugin
wordcount:
  enable: true
  # Display the word count of the article in post meta
  post_wordcount: true
  # Display the time to read the article in post meta
  min2read: true
  # Display the total word count of the website in aside's webinfo
  total_wordcount: true

# Busuanzi count for PV / UV in site
busuanzi:
  site_uv: false
  site_pv: false
  page_pv: false

# --------------------------------------
# Math
# --------------------------------------

# About the per_page
# if you set it to true, it will load mathjax/katex script in each page
# if you set it to false, it will load mathjax/katex script according to your setting (add the 'mathjax: true' or 'katex: true' in page's front-matter)
math:
  # Choose: mathjax, katex
  # Leave it empty if you don't need math
  use: katex
  per_page: false
  hide_scrollbar: false

  katex:
    # Enable the copy KaTeX formula
    copy_tex: true

# --------------------------------------
# Search
# --------------------------------------

search:
  # Choose: algolia_search / local_search / docsearch
  # leave it empty if you don't need search
  use: local_search
  placeholder: 搜索文章……

  # Local Search
  local_search:
    # Preload the search data when the page loads.
    preload: false
    # Show top n results per article, show all results by setting to -1
    top_n_per_article: 1
    # Unescape html strings to the readable one.
    unescape: true
    # Enable pagination for search results
    pagination:
      enable: false
      # Number of search results per page
      hitsPerPage: 8
    CDN:

# --------------------------------------
# Share System
# --------------------------------------

share:
  # Choose: sharejs / addtoany
  # Leave it empty if you don't need share
  use: addtoany

  # AddToAny
  # https://www.addtoany.com/
  addtoany:
    item: facebook,x,wechat,email,copy_link

# --------------------------------------
# Comments System
# --------------------------------------

comments:
  # Up to two comments system, the first will be shown as default
  # Leave it empty if you don't need comments
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo/Giscus/Remark42/Artalk
  # Format of two comments system : Disqus,Waline
  use: waline
  # Display the comment name next to the button
  text: true
  # Lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: true
  # Display comment count in post's top_img
  count: true
  # Display comment count in Home Page
  card_post_count: true

# Waline - A simple comment system with backend support fork from Valine
# https://waline.js.org/
waline:
  serverURL: https://waline.mtueih.com
  bg:
  # Use Waline pageview count as the page view count
  pageview: false
  option:
    reaction: true

# --------------------------------------
# Analysis
# --------------------------------------

# https://tongji.baidu.com/web/welcome/login
baidu_analytics:

# https://analytics.google.com/analytics/web/
google_analytics:

# https://www.cloudflare.com/zh-tw/web-analytics/
cloudflare_analytics:

# https://clarity.microsoft.com/
microsoft_clarity:

# https://umami.is/
umami_analytics:
  enable: true
  # For self-hosted setups, configure the hostname of the Umami instance
  serverURL: https://umami.mtueih.com
  script_name: script.js
  website_id: 54aff98e-4d0d-4976-8d2f-62e1435c436d
  option:
  UV_PV:
    site_uv: true
    site_pv: true
    page_pv: true
    # Umami Cloud (API key) / self-hosted Umami (token)
    token: dwWg1uEBniuN8kL95SPS3MVGynRV264Ep70lp8B0DzUWP8NF7Qd09mMPNW9Q9IvOe/7DdehbgnLsGSqkY7ar4gOPSI78EgInxn4OOed7rI25PR4dbEx79Hpe8rNoW32i7vXzO0gVZccZqgSDdiAfL54tDBHFKSPv0ooUXW9oVQoQbiGd7UtC4hLmTfLZ4PcZw72ynkfip16MH5wH5DVK5riv7CHBUXLBBkx4IZiPo31vQ3i+INRKd74WKqmGfBA2ztXG56pmx0w20pq0D1usLdLq7OxPfvaFWVwmRKCpiGt8UoQ56Or3oCB8KDwXXhS4xlwNvCh+CXfLBUp6tLJyui8/CnAd318zLRc6FKI647Ta1ueGHAju39NPXNGy

# https://www.googletagmanager.com/
google_tag_manager:
  tag_id:
  # optional
  domain:

# --------------------------------------
# Advertisement
# --------------------------------------

# Google Adsense
google_adsense:
  enable: true
  auto_ads: true
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client: ca-pub-7277949175201118
  enable_page_level_ads: true

# Insert ads manually
# Leave it empty if you don't need ads
ad:
  # Insert ads in the index (every three posts)
  index:
  # Insert ads in aside
  aside:
  # Insert ads in the post (before pagination)
  post:

# --------------------------------------
# Verification
# --------------------------------------

# --------------------------------------
# Beautify / Effect
# --------------------------------------

# Theme color for customize
# Notice: color value must in double quotes like "#000" or may cause error!

# theme_color:
#   enable: true
#   main: "#49B1F5"
#   paginator: "#00c4b6"
#   button_hover: "#FF7242"
#   text_selection: "#00c4b6"
#   link_color: "#99a9bf"
#   meta_color: "#858585"
#   hr_color: "#A4D8FA"
#   code_foreground: "#F47466"
#   code_background: "rgba(27, 31, 35, .05)"
#   toc_color: "#00c4b6"
#   blockquote_padding_color: "#49b1f5"
#   blockquote_background_color: "#49b1f5"
#   scrollbar_color: "#49b1f5"
#   meta_theme_color_light: "ffffff"
#   meta_theme_color_dark: "#0d0d0d"

# Page Transition
enter_transitions: true

# Default display mode - light (default) / dark
display_mode: light

# Configuration for beautifying the content of the article
beautify:
  enable: true
  # Specify the field to beautify (site or post)
  field: site
  # Specify the icon to be used as a prefix for the title, such as '\f0c1'
  title_prefix_icon:
  # Specify the color of the title prefix icon, such as '#F47466'
  title_prefix_icon_color:

# Global font settings
# Don't modify the following settings unless you know how they work
font:
  global_font_size:
  code_font_size:
  font_family:
  code_font_family:

# Font settings for the site title and site subtitle
blog_title_font:
  font_link:
  font_family:

# The setting of divider icon
hr_icon:
  enable: true
  # The unicode value of Font Awesome icon, such as '\3423'
  icon:
  icon_top:

# --------------------------------------
# Lightbox Settings
# --------------------------------------

# Choose: fancybox / medium_zoom
# https://github.com/francoischalifour/medium-zoom
# https://fancyapps.com/fancybox/
# Leave it empty if you don't need lightbox
lightbox: fancybox

# --------------------------------------
# Tag Plugins settings
# --------------------------------------

# Series
series:
  enable: false
  # Order by title or date
  orderBy: 'title'
  # Sort of order. 1, asc for ascending; -1, desc for descending
  order: 1
  number: true

# Mermaid
# https://github.com/mermaid-js/mermaid
mermaid:
  enable: true
  # Write Mermaid diagrams using code blocks
  code_write: true
  # built-in themes: default / forest / dark / neutral
  theme:
    light: default
    dark: dark

# chartjs
# see https://www.chartjs.org/docs/latest/
chartjs:
  enable: true
  # Do not modify unless you understand how they work.
  # The default settings are only used when the MD syntax is not specified.
  # General font color for the chart
  fontColor:
    light: 'rgba(0, 0, 0, 0.8)'
    dark: 'rgba(255, 255, 255, 0.8)'
  # General border color for the chart
  borderColor:
    light: 'rgba(0, 0, 0, 0.1)'
    dark: 'rgba(255, 255, 255, 0.2)'
  # Background color for scale labels on radar and polar area charts
  scale_ticks_backdropColor:
    light: 'transparent'
    dark: 'transparent'

# Note - Bootstrap Callout
note:
  # Note tag style values:
  #  - simple    bs-callout old alert style. Default.
  #  - modern    bs-callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: flat
  icons: true
  border_radius: 3
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: 0

# --------------------------------------
# Other Settings
# --------------------------------------

# Lazyload
# https://github.com/verlok/vanilla-lazyload
lazyload:
  enable: true
  # Use browser's native lazyload instead of vanilla-lazyload
  native: true
  # Specify the field to use lazyload (site or post)
  field: site
  placeholder: /img/loading.svg
  blur: true

# Open graph meta tags
# https://hexo.io/docs/helpers#open-graph
Open_Graph_meta:
  enable: true
  option:
    # twitter_card:
    # twitter_image:
    # twitter_id:
    # twitter_site:
    # google_plus:
    # fb_admins:
    # fb_app_id:

# Structured Data
# https://developers.google.com/search/docs/guides/intro-structured-data
structured_data:
  enable: true
  # Alternate name for the site, used in structured data
  # Format: ['name1', 'name2']
  alternate_name:

# Add the vendor prefixes to ensure compatibility
css_prefix: true

# Inject
# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
inject:
  head:
    # - <link rel="stylesheet" href="/xxx.css">
    - <link rel="stylesheet" href="/self/prism-solarizedlight.css">
    - <link rel="stylesheet" href="/self/prism-solarized-dark-atom.css">
  bottom:
    # - <script src="xxxx"></script>

# CDN Settings
# Don't modify the following settings unless you know how they work
CDN:
  # The CDN provider for internal and third-party scripts
  # Options for both: local/jsdelivr/unpkg/cdnjs/custom
  # Note: Dev version can only use 'local' for internal scripts
  # Note: When setting third-party scripts to 'local', you need to install hexo-butterfly-extjs
  internal_provider: local
  third_party_provider: jsdelivr

  # Add version number to url, true or false
  version: true

  # Custom format
  # For example: https://cdn.staticfile.org/${cdnjs_name}/${version}/${min_cdnjs_file}
  custom_format:

  option:
    # abcjs_basic_js:
    # activate_power_mode:
    # algolia_js:
    # algolia_search:
    # aplayer_css:
    # aplayer_js:
    # artalk_css:
    # artalk_js:
    # blueimp_md5:
    # busuanzi:
    # canvas_fluttering_ribbon:
    # canvas_nest:
    # canvas_ribbon:
    # chartjs:
    # click_heart:
    # clickShowText:
    # disqusjs:
    # disqusjs_css:
    # docsearch_css:
    # docsearch_js:
    # egjs_infinitegrid:
    # fancybox:
    # fancybox_css:
    # fireworks:
    # fontawesome:
    # gitalk:
    # gitalk_css:
    # giscus:
    # instantpage:
    # katex:
    # katex_copytex:
    # lazyload:
    # local_search:
    # main:
    # main_css:
    # mathjax:
    # medium_zoom:
    # mermaid:
    # meting_js:
    # prismjs_autoloader:
    # prismjs_js:
    # prismjs_lineNumber_js:
    # pjax:
    # sharejs:
    # sharejs_css:
    # snackbar:
    # snackbar_css:
    # translate:
    # twikoo:
    # typed:
    # utils:
    # valine:
    # waline_css:
    # waline_js:
