# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 狼魔宇个人博客
author: 狼魔宇
language: zh-CN
timezone: Asia/Shanghai

# URL
url: https://www.mtueih.com
permalink: blog/:titleSlugified/
pretty_urls:
  trailing_index: false
  trailing_html: false

# Writing
new_post_name: :year/:month/:title.md
filename_case: 1
future: false
syntax_highlighter: prismjs
prismjs:
  preprocess: true
  line_number: true
  tab_replace: "    "
  exclude_languages: ["mermaid"]

# Metadata elements
meta_generator: false

# Date / Time format
date_format: YYYY 年 M 月 D 日
time_format: HH:mm

# Category & Tag
category_map:
  "教程": "tutorial"
  "软件安装": "software-installation"
  "编程": "programming"
  "C/C++": "c-cpp"
  "环境搭建": "environment-setup"
tag_map:
  "MinGW-w64": "mingw-w64"
  "GCC": "gcc"
  "MSYS2": "msys2"
  "Windows": "windows"
  "C": "c"
  "C++": "cpp"

# Extensions
theme: butterfly

# Deployment
deploy:
  type: git
  repository: git@github.com:mtueih/mtueih.github.io.git
  branch: main

# Plugins
markdown:
  plugins:
    - '@renbaoshuo/markdown-it-katex'